version: "3"
services:
  app:
    image: 'riobueno/apacahe-swat'
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports: 
      - "8002:80"

  #docker-compose up -d
  #docker-compose down
