services:
  app:
#    build: .
    image: 'miapp:1.1'
    restart: unless-stopped
    container_name: miapp
    volumes:
      - ./:/var/www/html
    ports: 
      - "8003:8080"


  #docker build -t miapp.1.1 .
  #docker-compose up -d
  #docker-compose down
